"""Add assignment windows, activity and separate proctoring

Revision ID: 0010_bpmn_workflows
Revises: 0009_catalog_revision
Create Date: 2026-09-20 13:25:46.155527
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0010_bpmn_workflows"
down_revision: str | None = "0009_catalog_revision"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_activities",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=100), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_user_activities_actor_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_activities_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_activities")),
    )
    op.create_index(
        op.f("ix_user_activities_user_id"), "user_activities", ["user_id"], unique=False
    )
    op.create_table(
        "user_photos",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_photos_user_id_users")
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_photos")),
    )
    op.create_table(
        "teaching_messages",
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["training_groups.id"],
            name=op.f("fk_teaching_messages_group_id_training_groups"),
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"], ["users.id"], name=op.f("fk_teaching_messages_teacher_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teaching_messages")),
    )
    op.create_index(
        op.f("ix_teaching_messages_teacher_id"), "teaching_messages", ["teacher_id"], unique=False
    )
    op.create_table(
        "message_recipients",
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["teaching_messages.id"],
            name=op.f("fk_message_recipients_message_id_teaching_messages"),
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["users.id"], name=op.f("fk_message_recipients_student_id_users")
        ),
        sa.PrimaryKeyConstraint("message_id", "student_id", name=op.f("pk_message_recipients")),
    )
    op.create_index(
        op.f("ix_message_recipients_student_id"), "message_recipients", ["student_id"], unique=False
    )
    op.create_table(
        "proctoring_events",
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("command_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("client_occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"], ["attempts.id"], name=op.f("fk_proctoring_events_attempt_id_attempts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proctoring_events")),
        sa.UniqueConstraint(
            "attempt_id", "command_id", name=op.f("uq_proctoring_events_attempt_id")
        ),
    )
    op.create_index(
        op.f("ix_proctoring_events_attempt_id"), "proctoring_events", ["attempt_id"], unique=False
    )
    op.add_column("lessons", sa.Column("available_from", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "lessons", sa.Column("available_until", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        op.f("ix_lessons_available_until"), "lessons", ["available_until"], unique=False
    )
    op.create_check_constraint(
        op.f("ck_lessons_availability_order"),
        "lessons",
        "available_until IS NULL OR available_from IS NULL OR available_until > available_from",
    )
    op.add_column(
        "scenarios",
        sa.Column("is_archived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scenarios", "is_archived")
    op.drop_index(op.f("ix_lessons_available_until"), table_name="lessons")
    op.drop_constraint(op.f("ck_lessons_availability_order"), "lessons", type_="check")
    op.drop_column("lessons", "available_until")
    op.drop_column("lessons", "available_from")
    op.drop_index(op.f("ix_proctoring_events_attempt_id"), table_name="proctoring_events")
    op.drop_table("proctoring_events")
    op.drop_index(op.f("ix_message_recipients_student_id"), table_name="message_recipients")
    op.drop_table("message_recipients")
    op.drop_index(op.f("ix_teaching_messages_teacher_id"), table_name="teaching_messages")
    op.drop_table("teaching_messages")
    op.drop_table("user_photos")
    op.drop_index(op.f("ix_user_activities_user_id"), table_name="user_activities")
    op.drop_table("user_activities")
    # ### end Alembic commands ###
