"""telephony

Revision ID: 0021_telephony
Revises: 0020_disband_groups
Create Date: 2026-09-23 14:03:33.451666
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0021_telephony"
down_revision: str | None = "0020_disband_groups"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("training_calls", sa.Column("request_fingerprint", sa.String(64)))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "speech_assets",
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("voice", sa.String(length=100), nullable=False),
        sa.Column("generator_version", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("file_key", sa.String(length=64), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("leased_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_speech_assets")),
        sa.UniqueConstraint("fingerprint", name=op.f("uq_speech_assets_fingerprint")),
    )
    op.create_table(
        "call_cues",
        sa.Column("scenario_card_id", sa.Uuid(), nullable=False),
        sa.Column("contact_key", sa.String(length=100), nullable=False),
        sa.Column("contact_name", sa.String(length=255), nullable=False),
        sa.Column("audio_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["audio_id"], ["speech_assets.id"], name=op.f("fk_call_cues_audio_id_speech_assets")
        ),
        sa.ForeignKeyConstraint(
            ["scenario_card_id"],
            ["scenario_cards.id"],
            name=op.f("fk_call_cues_scenario_card_id_scenario_cards"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_call_cues")),
        sa.UniqueConstraint(
            "scenario_card_id", "contact_key", name=op.f("uq_call_cues_scenario_card_id")
        ),
    )
    op.create_table(
        "telephony_stations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("endpoint", sa.String(length=64), nullable=False),
        sa.Column("sip_password", sa.String(length=128), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=True),
        sa.Column("attempt_id", sa.Uuid(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("provisioned", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("error", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "endpoint ~ '^[A-Za-z0-9_][A-Za-z0-9_-]{0,63}$'",
            name=op.f("ck_telephony_stations_endpoint"),
        ),
        sa.CheckConstraint(
            "mode IN ('external', 'browser', 'phone')", name=op.f("ck_telephony_stations_mode")
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"], ["attempts.id"], name=op.f("fk_telephony_stations_attempt_id_attempts")
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["users.id"], name=op.f("fk_telephony_stations_student_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telephony_stations")),
        sa.UniqueConstraint("attempt_id", name=op.f("uq_telephony_stations_attempt_id")),
        sa.UniqueConstraint("provider", "endpoint", name=op.f("uq_telephony_stations_provider")),
        sa.UniqueConstraint("student_id", name=op.f("uq_telephony_stations_student_id")),
    )
    op.create_table(
        "telephony_events",
        sa.Column("call_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("event_id", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["call_id"],
            ["training_calls.id"],
            name=op.f("fk_telephony_events_call_id_training_calls"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telephony_events")),
        sa.UniqueConstraint("provider", "event_id", name=op.f("uq_telephony_events_provider")),
    )
    op.create_index(
        op.f("ix_telephony_events_call_id"), "telephony_events", ["call_id"], unique=False
    )
    op.add_column("training_calls", sa.Column("station_id", sa.Uuid(), nullable=True))
    op.add_column("training_calls", sa.Column("audio_id", sa.Uuid(), nullable=True))
    op.add_column(
        "training_calls",
        sa.Column("direction", sa.String(length=16), server_default="outgoing", nullable=False),
    )
    op.add_column(
        "training_calls",
        sa.Column("transport", sa.String(length=16), server_default="manual", nullable=False),
    )
    op.add_column(
        "training_calls",
        sa.Column("provider", sa.String(length=64), server_default="local", nullable=False),
    )
    op.add_column(
        "training_calls", sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "training_calls",
        sa.Column("cancel_requested", sa.Boolean(), server_default="false", nullable=False),
    )
    op.alter_column("training_calls", "response_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("training_calls", "contact_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("training_calls", "target_service_id", existing_type=sa.UUID(), nullable=True)
    op.create_foreign_key(
        op.f("fk_training_calls_audio_id_speech_assets"),
        "training_calls",
        "speech_assets",
        ["audio_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_training_calls_station_id_telephony_stations"),
        "training_calls",
        "telephony_stations",
        ["station_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column("training_calls", "request_fingerprint")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_training_calls_station_id_telephony_stations"),
        "training_calls",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_training_calls_audio_id_speech_assets"), "training_calls", type_="foreignkey"
    )
    op.alter_column("training_calls", "target_service_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("training_calls", "contact_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("training_calls", "response_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("training_calls", "cancel_requested")
    op.drop_column("training_calls", "dispatched_at")
    op.drop_column("training_calls", "provider")
    op.drop_column("training_calls", "transport")
    op.drop_column("training_calls", "direction")
    op.drop_column("training_calls", "audio_id")
    op.drop_column("training_calls", "station_id")
    op.drop_index(op.f("ix_telephony_events_call_id"), table_name="telephony_events")
    op.drop_table("telephony_events")
    op.drop_table("telephony_stations")
    op.drop_table("call_cues")
    op.drop_table("speech_assets")
    # ### end Alembic commands ###
