import type { IncidentCard } from "./types";

export const demoIncidents: readonly IncidentCard[] = [
  {
    id: "378879302",
    displayNumber: 378879302,
    createdDate: "17.09.2026",
    operatorNumber: "0",
    workstation: "4",
    createdAt: "10:47:36",
    channel: "101",
    origin: "generated",
    fields: {
      categoryId: "traffic",
      address: {
        district: "ЮАО",
        area: "Донской район",
        street: "Третье транспортное кольцо",
        house: "12",
        building: "",
        apartment: "",
        entrance: "",
        floor: "",
        description: "",
      },
      callerName: "Соколов П. Н.",
      phones: {
        callerId: "+7 900 000-00-01",
        provided: "+7 900 000-00-01",
        onSite: "",
      },
      victimsCount: 0,
      description: "Удар в ограждение, пострадавших нет.",
      operatorAction: "",
      services: [],
      status: "in_progress",
    },
  },
  {
    id: "378879304",
    displayNumber: 378879304,
    createdDate: "17.09.2026",
    operatorNumber: "0",
    workstation: "4",
    createdAt: "10:46:12",
    channel: "101",
    origin: "generated",
    fields: {
      categoryId: "fire",
      address: {
        district: "СВАО",
        area: "Алтуфьевский район",
        street: "ул. Гончарова",
        house: "13",
        building: "",
        apartment: "",
        entrance: "2",
        floor: "",
        description: "",
      },
      callerName: "Иванова М. С.",
      phones: {
        callerId: "+7 900 000-00-02",
        provided: "+7 900 000-00-02",
        onSite: "",
      },
      victimsCount: null,
      description: "Запах дыма в подъезде жилого дома.",
      operatorAction: "",
      services: [],
      status: "not_notified",
    },
  },
  {
    id: "378879308",
    displayNumber: 378879308,
    createdDate: "17.09.2026",
    operatorNumber: "0",
    workstation: "4",
    createdAt: "10:44:21",
    channel: "102",
    origin: "generated",
    fields: {
      categoryId: "utility",
      address: {
        district: "ЦАО",
        area: "Тверской район",
        street: "ул. Лесная",
        house: "24",
        building: "",
        apartment: "",
        entrance: "",
        floor: "",
        description: "",
      },
      callerName: "Петров А. А.",
      phones: {
        callerId: "+7 900 000-00-03",
        provided: "+7 900 000-00-03",
        onSite: "",
      },
      victimsCount: 0,
      description: "Отключение холодного водоснабжения.",
      operatorAction: "",
      services: [],
      status: "in_progress",
    },
  },
  {
    id: "378879314",
    displayNumber: 378879314,
    createdDate: "17.09.2026",
    operatorNumber: "0",
    workstation: "4",
    createdAt: "10:42:04",
    channel: "103",
    origin: "generated",
    fields: {
      categoryId: "medical",
      address: {
        district: "СВАО",
        area: "Останкинский район",
        street: "ул. Академика Королёва",
        house: "24",
        building: "1",
        apartment: "56",
        entrance: "3",
        floor: "7",
        description: "",
      },
      callerName: "Орлова Е. В.",
      phones: {
        callerId: "+7 900 000-00-04",
        provided: "+7 900 000-00-04",
        onSite: "+7 900 000-00-04",
      },
      victimsCount: 1,
      description: "Ребёнок получил травму при падении.",
      operatorAction: "Вызов передан бригаде скорой помощи.",
      services: ["103"],
      status: "closed",
    },
  },
];
