export const fieldLabels: Record<string, string> = {
  gender: "Пол",
  age: "Возраст",
  height_cm: "Рост, см",
  weight_kg: "Вес, кг",
  appearance: "Внешность",
  categoryId: "Тип происшествия",
  classifier_entry_id: "Тип происшествия",
  callerName: "Заявитель",
  address: "Адрес",
  phones: "Телефоны",
  buildingFloors: "Этажность",
  caller_name: "Заявитель",
  caller_phone: "Телефон",
  caller_details: "Сведения о заявителе",
  callerId: "АОН",
  provided: "Предоставленный",
  onSite: "На месте",
  address_text: "Адрес",
  address_details: "Сведения об адресе",
  description: "Сообщение",
  victim_details: "Пострадавшие",
  features: "Признаки",
  victimsCount: "Количество пострадавших",
  additional_fields: "Дополнительные сведения",
  details: "Уточнения",
  operatorAction: "Комментарий оператора",
  country: "Страна",
  region: "Субъект",
  locality: "Населённый пункт",
  object: "Объект",
  district: "Округ",
  area: "Район",
  street: "Улица",
  house: "Дом",
  building: "Корпус",
  structure: "Строение",
  apartment: "Квартира",
  entrance: "Подъезд",
  floor: "Этаж",
  doorCode: "Код",
  classificationDescription: "Уточнение типа",
  callerStatus: "Статус заявителя",
  callerGender: "Пол",
  callerAge: "Возраст",
  foreignLanguage: "Иностранный язык",
  hasVictims: "Пострадавшие",
  noContact: "Нет контакта",
  callDropped: "Срыв звонка",
  refusedAmbulance: "Нет на месте / Отказ от скорой",
  blocked: "Нет доступа / Заблокированные",
  clarifications: "Уточняющие признаки",
  has_victims: "Есть пострадавшие",
};
